INSERT INTO TEST VALUES(1, 'Hello');
INSERT INTO TEST VALUES(2, 'World!');
INSERT INTO TEST VALUES(3, 'This');
INSERT INTO TEST VALUES(4, 'is');
INSERT INTO TEST VALUES(5, 'H2');
INSERT INTO TEST VALUES(6, 'db');